// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Carrinho struct {
	ID        int32
	ClienteID sql.NullInt32
	UserID    sql.NullInt32
	Total     sql.NullString
	Status    string
	CreatedAt sql.NullTime
}

type Categorium struct {
	IDCategoria int32
	Nome        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Cliente struct {
	IDCliente    int32
	NomeFantasia sql.NullString
	Name         string
	Email        string
	Telefone     sql.NullString
	Endereco     sql.NullString
	CreatedAt    sql.NullTime
}

type Documento struct {
	ID              int32
	ClienteID       sql.NullInt32
	TipoDocumento   string
	NumeroDocumento string
	Cpf             sql.NullString
	CreatedAt       sql.NullTime
}

type Estoque struct {
	ID              int32
	IDProduto       sql.NullInt32
	QuantidadeAtual int32
	UpdatedAt       sql.NullTime
}

type ItensNoCarrinho struct {
	ID            int32
	CartID        sql.NullInt32
	ProdutoID     sql.NullInt32
	Quantidade    int32
	PrecoUnitario string
	CreatedAt     sql.NullTime
}

type Pedido struct {
	IDPedido   int32
	IDCliente  sql.NullInt32
	CarrinhoID sql.NullInt32
	Status     string
	Total      string
	CreatedAt  sql.NullTime
}

type Produto struct {
	IDProduto   int32
	Name        string
	Price       string
	Referencia  sql.NullString
	CategoriaID sql.NullInt32
	CreatedAt   sql.NullTime
}

type Taxa struct {
	ID        int32
	CartID    sql.NullInt32
	Descricao string
	Value     string
	CreatedAt sql.NullTime
}

type User struct {
	IDUser    int32
	Nome      string
	Email     string
	Senha     string
	CreatedAt sql.NullTime
}
