// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Cart struct {
	ID     int64
	UserID int64
}

type CartItem struct {
	ID        int64
	CartID    sql.NullInt32
	ProductID int64
	Quantity  int64
	Price     string
}

type Product struct {
	ID    int32
	Name  string
	Price string
}
